"""Durable, budgeted agent loop with explicit stop conditions and resume."""

from keelgate.loop.checkpoint import (
    CheckpointStore,
    HistoryCheckpointStore,
    InMemoryCheckpointStore,
    SqliteCheckpointStore,
    StaleCheckpointError,
    default_checkpointer,
)
from keelgate.loop.engine import (
    DEFAULT_SYSTEM_PROMPT,
    ContextSource,
    Loop,
    LoopResult,
    OutcomeConfirmer,
    RunExistsError,
    RunNotFoundError,
)
from keelgate.loop.kinds import (
    READ_ONLY,
    MonitorLoop,
    MonitorSummary,
    Schedule,
    VerificationLoop,
)
from keelgate.loop.replay import (
    Divergence,
    NotReplayableError,
    RecordedAction,
    RecordedStep,
    Recording,
    ReplayReport,
    diff,
    find_run,
    replay,
)
from keelgate.loop.roles import (
    AcceptAllVerifier,
    CallableVerifier,
    LLMPlanner,
    LLMVerifier,
    Plan,
    Planner,
    PlanRequest,
    ProposedAction,
    Verdict,
    VerdictDecision,
    Verifier,
    VerifyRequest,
)
from keelgate.loop.runner import InProcessRunner, LoopOutcome, LoopRunner, LoopSpec
from keelgate.loop.state import (
    ActionOutcome,
    ActionStatus,
    LoopState,
    LoopType,
    Phase,
    PlannedAction,
    StopReason,
)
from keelgate.loop.stop import GoalPredicate, StopConditions

__all__ = [
    "DEFAULT_SYSTEM_PROMPT",
    "READ_ONLY",
    "AcceptAllVerifier",
    "ActionOutcome",
    "ActionStatus",
    "CallableVerifier",
    "CheckpointStore",
    "ContextSource",
    "Divergence",
    "GoalPredicate",
    "HistoryCheckpointStore",
    "InMemoryCheckpointStore",
    "InProcessRunner",
    "LLMPlanner",
    "LLMVerifier",
    "Loop",
    "LoopOutcome",
    "LoopResult",
    "LoopRunner",
    "LoopSpec",
    "LoopState",
    "LoopType",
    "MonitorLoop",
    "MonitorSummary",
    "NotReplayableError",
    "OutcomeConfirmer",
    "Phase",
    "Plan",
    "PlanRequest",
    "PlannedAction",
    "Planner",
    "ProposedAction",
    "RecordedAction",
    "RecordedStep",
    "Recording",
    "ReplayReport",
    "RunExistsError",
    "RunNotFoundError",
    "Schedule",
    "SqliteCheckpointStore",
    "StaleCheckpointError",
    "StopConditions",
    "StopReason",
    "Verdict",
    "VerdictDecision",
    "VerificationLoop",
    "Verifier",
    "VerifyRequest",
    "default_checkpointer",
    "diff",
    "find_run",
    "replay",
]
